export class Hierarchy {
    sctId: string;
    name: string;
    semTag: string;
    newlyCreated: number;
    relationships: number;
    inactivations: number;
    changedStatus: number;
    changed: number;
    inactivated: number;
    reactivated: number;
    newWithNewConcept: number;
    sd: number;
    p: number;
    total: number;
    totalActive: number;
    conceptsAffected: number;
    ambiguous: number;
    movedElsewhere: number;
    conceptNonCurrent: number;
    duplicate: number;
    erroneous: number;
    inappropriate: number;
    limited: number;
    outdated: number;
    pendingMove: number;
    nonConformance: number;
    notEquivalent: number;
}
